export const ENDPOINTS = {
  CONSTANTS: '/constants',
  CHECK_IN: '/auth/checkin',
  CHECK_OUT: '/auth/checkout',
  USER_VERIFY: '/auth/verify',
  PRODUCT_SEARCH: '/products/search',
  AUCTION_SEARCH: '/auctions/search',
  AUCTION_REGISTER: '/auctions',
  AUCTION_ITEM: '/auctions',
  SALES_ITEM: '/saleitems',
  COMPANY_LIST: '/companies',
  NOTIFICATION: '/notifications',
  MY_DEVICES: '/users/me/devices',
  USER: '/users',
};
