name: Deploy Notification Lambda

on:
  push:
    paths:
      - 'apps/lambda/notification/**'
      - '.github/workflows/deploy-lambda.yml'
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for Lambda changes
        id: check
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep "^apps/lambda/notification/" || echo "")
          if [ ! -z "$CHANGED" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd apps/lambda/notification
          npm install

      - name: Build Lambda
        run: |
          cd apps/lambda/notification
          npm run package
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Deploy with CDK
        run: |
          cd apps/lambda/notification
          npm run deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}